services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    healthcheck:
      test: wget --spider -q http://localhost:9090/-/healthy || exit 1
      interval: 5s
      retries: 3
      timeout: 3s

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      prometheus:
        condition: service_healthy
        restart: true

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  grafana-storage:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: