spring.application.name=taskflow

management.endpoints.web.base-path=/api/actuator
management.endpoints.web.exposure.include=health,prometheus

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
